import {getSessionUser} from '@/lib/auth';
import {db,fail,sameOrigin} from '@/lib/server';
import {spotSchema,distance} from '@/lib/models';
import {z} from 'zod';
export async function POST(req:Request){try{sameOrigin(req);const user=await getSessionUser();if(!user)return Response.json({error:'Sign in to continue.'},{status:401});const d=db(),uid=user.userId,b=z.record(z.unknown()).parse(await req.json()),now=Date.now();await d.prepare('INSERT OR IGNORE INTO profiles (id,name) VALUES (?,?)').bind(uid,user.fullName||'Explorer').run();
if(b.type==='spot'){const s=spotSchema.parse(b.spot),id=s.id||crypto.randomUUID();const old=await d.prepare('SELECT owner FROM spots WHERE id=?').bind(id).first();if(old&&old.owner!==uid)throw Error('You can only edit your own spots');for(const path of [...s.photos,...(s.video?[s.video]:[])]){const row=await d.prepare('SELECT user FROM uploads WHERE id=?').bind(path.split('/').pop()).first();if(row?.user!==uid)throw Error('Choose your uploaded photos');}await d.prepare('INSERT INTO spots (id,owner,data,created) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(id,uid,JSON.stringify({...s,id}),now).run();return Response.json({id});}
if(b.type==='toggle'){const kind=z.enum(['save','like','visit','confirm','follow']).parse(b.kind),id=z.string().min(1).max(150).parse(b.id),active=z.boolean().parse(b.active);if(id.startsWith('demo-')&&!['demo-falls','demo-ridge','demo-lake'].includes(id))throw Error('Unknown sample');if(id.startsWith('demo-')&&['confirm','follow'].includes(kind))throw Error('This action requires a real community spot');if(!id.startsWith('demo-')){const exists=await d.prepare(kind==='follow'?'SELECT id FROM profiles WHERE id=?':'SELECT id FROM spots WHERE id=?').bind(id).first();if(!exists)throw Error('This item no longer exists');}if(kind==='confirm'){const v=await d.prepare("SELECT user FROM actions WHERE user=? AND spot=? AND kind='visit'").bind(uid,id).first();if(!v)throw Error('Mark your visit first');}if(active){await d.prepare('INSERT OR IGNORE INTO actions (user,spot,kind,created) VALUES (?,?,?,?)').bind(uid,id,kind,now).run();}else{await d.prepare('DELETE FROM actions WHERE user=? AND spot=? AND kind=?').bind(uid,id,kind).run();if(kind==='visit')await d.batch([d.prepare("DELETE FROM actions WHERE user=? AND spot=? AND kind IN ('confirm','checkin')").bind(uid,id),d.prepare("DELETE FROM comments WHERE user=? AND spot=? AND kind='review'").bind(uid,id)]);}return Response.json({ok:true});}
if(b.type==='checkin'){const p=z.object({id:z.string().uuid(),lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180),accuracy:z.number().min(0).max(150)}).parse(b);const row=await d.prepare('SELECT data FROM spots WHERE id=?').bind(p.id).first<{data:string}>();if(!row)throw Error('Spot not found');const s=JSON.parse(row.data);if(s.lat===null||s.lng===null)throw Error('This spot has no location pin');if(distance(p.lat,p.lng,s.lat,s.lng)>.2)throw Error('Check in when you are within 200 metres of this spot');await d.batch(['visit','checkin'].map(k=>d.prepare('INSERT OR IGNORE INTO actions (user,spot,kind,created) VALUES (?,?,?,?)').bind(uid,p.id,k,now)));return Response.json({ok:true});}
if(b.type==='comment'){const v=z.object({spot:z.string(),kind:z.enum(['review','tip','alert']),text:z.string().min(3).max(2000),rating:z.number().int().min(1).max(5).optional()}).parse(b);if(v.spot.startsWith('demo-'))throw Error('Reviews and alerts are available on community spots');const spot=await d.prepare('SELECT id FROM spots WHERE id=?').bind(v.spot).first();if(!spot)throw Error('Spot not found');if(v.kind==='review'){if(!v.rating)throw Error('Choose a star rating');const visit=await d.prepare("SELECT user FROM actions WHERE user=? AND spot=? AND kind='visit'").bind(uid,v.spot).first();if(!visit)throw Error('Mark this spot as visited before reviewing');const prev=await d.prepare("SELECT id FROM comments WHERE user=? AND spot=? AND kind='review'").bind(uid,v.spot).first();if(prev)throw Error('You have already reviewed this spot');}await d.prepare('INSERT INTO comments (id,user,spot,kind,text,rating,created) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),uid,v.spot,v.kind,v.text,v.rating||null,now).run();return Response.json({ok:true});}
if(b.type==='profile'){const p=z.object({name:z.string().min(2).max(80),bio:z.string().max(500),region:z.string().max(100)}).parse(b);await d.prepare('UPDATE profiles SET name=?,bio=?,region=? WHERE id=?').bind(p.name,p.bio,p.region,uid).run();return Response.json({ok:true});}
if(b.type==='trip'){const t=z.object({name:z.string().min(2).max(100),date:z.string().regex(/^(?:[0-9]{4}-[0-9]{2}-[0-9]{2})?$/),spots:z.array(z.string().max(150)).min(1).max(20)}).parse(b);if(new Set(t.spots).size!==t.spots.length)throw Error('Each stop can appear once');for(const id of t.spots){if(['demo-falls','demo-ridge','demo-lake'].includes(id))continue;const exists=await d.prepare('SELECT id FROM spots WHERE id=?').bind(id).first();if(!exists)throw Error('One of the selected spots is no longer available');}const id=crypto.randomUUID();await d.prepare('INSERT INTO trips (id,user,name,date,spots,created) VALUES (?,?,?,?,?,?)').bind(id,uid,t.name,t.date,JSON.stringify(t.spots),now).run();return Response.json({id});}
if(b.type==='deleteTrip'){await d.prepare('DELETE FROM trips WHERE id=? AND user=?').bind(String(b.id),uid).run();return Response.json({ok:true});}
if(b.type==='report'){const r=z.object({spot:z.string().max(150),reason:z.string().min(5).max(1000)}).parse(b);await d.prepare('INSERT INTO reports (id,user,spot,reason,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),uid,r.spot,r.reason,now).run();return Response.json({ok:true});}
throw Error('Unknown action');}catch(e){return fail(e)}}
