"use client";
import {useState} from 'react';
import {Camera,MapPin,ChevronRight,ChevronLeft,Upload,Check,LocateFixed,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {toast} from 'sonner';
import {categories,spotSchema,type Spot} from '@/lib/models';
import SpotMap from './spot-map';
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export function Tick({checked,onChange,children}:{checked:boolean;onChange:(b:boolean)=>void;children:React.ReactNode}){return <label className="tick"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>}
const blank={title:'',tagline:'',description:'',region:'',categories:[] as string[],photos:[] as string[],video:'',lat:null as number|null,lng:null as number|null,directions:'',landmark:'',bestTime:'',season:'All year',difficulty:'Easy',crowd:'Quiet',duration:'',safety:'',hazards:[] as string[],restrictions:'',permits:'',emergency:'',packing:['Drinking water','Walking shoes','First-aid kit','Charged phone','Litter bag'],sensitive:false,flora:'',story:'',accessibility:'',route:[] as [number,number][]};
const stages=['The place','Location','Photos','Field notes','Safety','Review'];
export default function ListingForm({initial,onClose,onSave}:{initial?:Spot;onClose:()=>void;onSave:(s:any)=>Promise<void>}){const [v,setV]=useState<any>(initial||blank),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[attest,setAttest]=useState(false),[draw,setDraw]=useState(false);const set=(k:string,a:any)=>setV((s:any)=>({...s,[k]:a}));
function field(k:string,label:string,placeholder='',multiline=false){return <label className="field">{label}{multiline?<textarea value={v[k]??''} onChange={e=>set(k,e.target.value)} placeholder={placeholder} rows={3}/>:<input value={v[k]??''} onChange={e=>set(k,e.target.value)} placeholder={placeholder}/>}</label>}
async function upload(files:FileList|null){if(!files)return;setBusy(true);try{let photoCount=v.photos.length;for(const f of Array.from(files)){if(f.type.startsWith('image/')&&photoCount>=10)throw Error('Up to 10 photos per spot');const form=new FormData();form.append('file',f);const r=await fetch('/api/upload',{method:'POST',body:form});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(f.type.startsWith('image/'))photoCount++;setV((s:any)=>f.type.startsWith('video/')?({...s,video:d.url}):({...s,photos:[...s.photos,d.url].slice(0,10)}));}toast.success('Upload complete');}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
function next(){if(step===0&&(!v.title.trim()||v.description.length<20||!v.categories.length)){toast.error('Add a name, at least 20 characters about the place, and a category.');return}if(step===1&&(v.region.length<2||v.directions.length<10)){toast.error('Add the nearest town and written directions.');return}if(step===2&&!v.photos.length){toast.error('Upload at least one photo you took.');return}setStep(step+1)}
async function submit(){const r=spotSchema.safeParse(v);if(!r.success){toast.error(r.error.issues[0].path.join('.')+': '+r.error.issues[0].message);return}if(!attest){toast.error('Confirm your visit and permission to share.');return}setBusy(true);try{await onSave(r.data);onClose()}catch{}finally{setBusy(false)}}
return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="flow-modal"><div className="eyebrow">PASS ON A LITTLE WONDER</div><DialogTitle className="serif modal-heading">{initial?'Edit your discovery':'Add a hidden spot'}</DialogTitle><DialogDescription>Places shared by people who have actually been there.</DialogDescription><div className="steps">{stages.map((s,i)=><button key={s} className={i===step?'current':i<step?'done':''} disabled={i>step} onClick={()=>setStep(i)}><span>{i<step?<Check size={12}/>:i+1}</span>{s}</button>)}</div><Progress value={(step+1)/6*100} className="h-1"/><div className="form-body">
{step===0&&<><div className="two-fields">{field('title','What do you call this place?','A name with a little story')}{field('tagline','One-line introduction','What makes it special?')}</div>{field('description','Tell us about the place','Describe what you found and why it’s worth slowing down for.',true)}<label className="field">What kind of place is it?</label><div className="chips">{categories.map(c=><button key={c} className={v.categories.includes(c)?'chip selected':'chip'} onClick={()=>set('categories',v.categories.includes(c)?v.categories.filter((x:string)=>x!==c):[...v.categories,c])}>{c}</button>)}</div></>}
{step===1&&<><div className="two-fields">{field('region','Nearest town, district & state','e.g. Pala, Kottayam, Kerala')}{field('landmark','A useful landmark','Village, junction, or trail entrance')}</div><SpotMap pin={v.lat!==null&&v.lng!==null?[v.lat,v.lng]:null} onPin={p=>{set('lat',p[0]);set('lng',p[1])}} route={v.route} draw={draw} onRoute={p=>set('route',[...v.route,p])}/><div className="row wrap"><button className="btn secondary" onClick={()=>{if(!navigator.geolocation){toast.error('Location is not supported');return}navigator.geolocation.getCurrentPosition(p=>{set('lat',p.coords.latitude);set('lng',p.coords.longitude)},()=>toast.error('Location unavailable. Drop a pin or enter coordinates.'))}}><LocateFixed size={16}/> Use my location</button><Tick checked={draw} onChange={setDraw}>Sketch walking route</Tick>{v.route.length>0&&<button className="text-button" onClick={()=>set('route',[])}>Clear route</button>}</div><div className="two-fields">{['lat','lng'].map((k,i)=><label className="field" key={k}>{i?'Longitude':'Latitude'}<input type="number" step="any" value={v[k]??''} onChange={e=>set(k,e.target.value===''?null:Number(e.target.value))}/></label>)}</div>{field('directions','How do you get there?','Include parking, the final walking path, and helpful landmarks. Written directions are required even with a pin.',true)}</>}
{step===2&&<><label className="upload-zone"><Camera size={32}/><strong>Show us what you discovered</strong><span>1–10 photos · JPG, PNG, WebP · up to 25 MB each</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>upload(e.target.files)}/><span className="btn secondary"><Upload size={15}/> {busy?'Uploading…':'Choose photos'}</span></label><div className="upload-grid">{v.photos.map((p:string,i:number)=><div key={p}><img src={p} alt={'Your upload '+(i+1)}/><button aria-label="Remove photo" onClick={()=>set('photos',v.photos.filter((_:string,j:number)=>i!==j))}><X size={14}/></button></div>)}</div><label className="field">Optional short video (MP4 or WebM, up to 25 MB)<input type="file" accept="video/mp4,video/webm" disabled={busy} onChange={e=>upload(e.target.files)}/></label>{v.video&&<p className="notice">Video uploaded <button onClick={()=>set('video','')}>Remove</button></p>}<p className="muted">Only upload media you own or have permission to share.</p></>}
{step===3&&<><div className="two-fields">{field('bestTime','Best time to visit','e.g. Sunrise, before 8 am')}{field('duration','Travel / walking time','e.g. 20 min from town + 15 min walk')}</div><div className="three-fields"><label className="field">Season<Choice label="Season" value={v.season} onChange={a=>set('season',a)} options={['All year','Winter','Summer','Monsoon']}/></label><label className="field">Difficulty<Choice label="Difficulty" value={v.difficulty} onChange={a=>set('difficulty',a)} options={['Easy','Moderate','Challenging']}/></label><label className="field">Crowd level<Choice label="Crowd" value={v.crowd} onChange={a=>set('crowd',a)} options={['Quiet','Moderately known','Busy weekends']}/></label></div>{field('accessibility','Accessibility','Steps, uneven paths, wheelchair access…')}{field('flora','What grows or lives here?','Birds, plants, wildlife you noticed')}{field('story','Your story (optional)','What will you remember about this place?',true)}</>}
{step===4&&<><label className="field">What should another explorer watch for?</label><div className="chips">{['Slippery rocks','Cliff edge','Flash-flood risk','Deep water','Wildlife','No phone network','Narrow road','Restricted land'].map(c=><button className={v.hazards.includes(c)?'chip caution selected':'chip'} key={c} onClick={()=>set('hazards',v.hazards.includes(c)?v.hazards.filter((x:string)=>x!==c):[...v.hazards,c])}>{c}</button>)}</div>{field('safety','Helpful safety notes','Tell people what to prepare for.',true)}<div className="two-fields">{field('restrictions','Restricted hours / activities','e.g. No entry after 5 pm. No fires.')}{field('permits','Permits or permissions','Who should visitors contact?')}</div>{field('emergency','Nearest emergency help','Hospital / forest office, distance and verified contact')}{field('packingText','Things to carry (one per line)','',true)}<button className="text-button" onClick={()=>set('packingText',v.packing.join('\n'))}>Start with suggested packing list</button><Tick checked={v.sensitive} onChange={a=>set('sensitive',a)}>This place is fragile. Ask visitors to take the Leave No Trace pledge.</Tick></>}
{step===5&&<><div className="review-preview">{v.photos[0]&&<img src={v.photos[0]} alt="Listing cover"/>}<div><span className="eyebrow">{v.categories.join(' · ')}</span><h2 className="serif">{v.title}</h2><p>{v.tagline}</p><p><MapPin size={14}/> {v.region}</p><span className="pill">Unconfirmed until other visitors confirm</span></div></div><p>{v.description}</p><div className="notice">{v.difficulty} · {v.crowd} · {v.season}<br/>{v.photos.length} photos · {v.lat===null?'Written directions':'Map pin + written directions'}{v.route.length>0?' · Walking route':''}</div><Tick checked={attest} onChange={setAttest}>I have visited this place, have permission to share these photos, and am not directing visitors onto restricted or private land without permission.</Tick></>}
</div><div className="form-footer"><button className="btn secondary" disabled={busy} onClick={()=>step?setStep(step-1):onClose()}><ChevronLeft size={16}/>{step?'Back':'Cancel'}</button><span className="muted">{step+1} of 6</span><button className="btn primary" disabled={busy} onClick={()=>{if(step===4&&v.packingText)set('packing',v.packingText.split('\n').map((s:string)=>s.trim()).filter(Boolean));step===5?submit():next()}}>{busy?'Saving…':step===5?'Share this spot':'Continue'}<ChevronRight size={16}/></button></div></DialogContent></Dialog>}
