import {z} from 'zod';
export const categories=['Waterfalls','Viewpoints','Trails','Lakes','Campsites','Stargazing','Caves','Riversides','Ruins'];
export const spotSchema=z.object({id:z.string().uuid().optional(),title:z.string().trim().min(3).max(100),tagline:z.string().max(180),description:z.string().trim().min(20).max(8000),region:z.string().trim().min(2).max(150),categories:z.array(z.enum(['Waterfalls','Viewpoints','Trails','Lakes','Campsites','Stargazing','Caves','Riversides','Ruins'])).min(1).max(9),photos:z.array(z.string().url()).min(1).max(10),video:z.string().url().optional().or(z.literal('')),lat:z.number().min(-90).max(90).nullable(),lng:z.number().min(-180).max(180).nullable(),directions:z.string().trim().min(10).max(5000),landmark:z.string().max(200),bestTime:z.string().max(300),season:z.string().max(60),difficulty:z.enum(['Easy','Moderate','Challenging']),crowd:z.enum(['Quiet','Moderately known','Busy weekends']),duration:z.string().max(100),safety:z.string().max(4000),hazards:z.array(z.string().max(80)).max(12),restrictions:z.string().max(2000),permits:z.string().max(1000),emergency:z.string().max(1000),packing:z.array(z.string().max(100)).max(30),sensitive:z.boolean(),flora:z.string().max(500),story:z.string().max(4000),accessibility:z.string().max(300),route:z.array(z.tuple([z.number().min(-90).max(90),z.number().min(-180).max(180)])).max(100).default([])}).refine(s=>(s.lat===null)===(s.lng===null),'Enter both coordinates or leave both blank');
export type Spot=z.infer<typeof spotSchema>&{id:string;owner:string;scout:string;created:number;demo?:boolean;saves?:number;rating?:number;confirmations?:number;reviewCount?:number;verified?:boolean};
export function distance(a:number,b:number,c:number,d:number){const rad=Math.PI/180;const v=Math.sin((c-a)*rad/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin((d-b)*rad/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
// A spot shows the blue verified tick if staff manually verified it, OR it
// has earned trust on its own: at least 3 other visitors confirmed it exists,
// or it has 3+ reviews averaging 4 stars or better.
export function isVerifiedSpot(s:{verified?:boolean;confirmations?:number;reviewCount?:number;rating?:number}){return !!s.verified||(s.confirmations||0)>=3||((s.reviewCount||0)>=3&&(s.rating||0)>=4);}
